# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 58b6d2d9090cd5d9ab22fa98eb140e03f5363ffc31c0b5c010b514023b59136ddcae82036930c3c587065197af1156a3a2c45eed78678f87c5e1e3a6cf6cdeaf

test:
  secret_key_base: 52a5242af296b005189d257b0f92b5bb2ac773652fa95a8e9f82fe8cb30d17bffc5fe288a72a42ad8592aa1c40f04f6b9c545a228c052ba287d7c16323dd5759

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
